# Generated by Django 2.2 on 2019-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardMon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard',
            name='Bay',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='贝位'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Box',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='箱区'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Col',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='列数'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='集装箱颜色（补充）'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='CtnNo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='箱号'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='CtnTyp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='箱型'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='CtnWegt',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='箱重'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Lay',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='层数'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='LoaVesTim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='装船日期'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Owner',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='持箱人'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='StrLoaUnlSig',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='直接装卸船'),
        ),
        migrations.AlterField(
            model_name='yard',
            name='UnloadPort',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='卸货港'),
        ),
    ]
