# Generated by Django 2.2 on 2019-05-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardMon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='CtnNo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='箱号'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='CtnTyp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='箱型'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='CtnWegt',
            field=models.FloatField(blank=True, null=True, verbose_name='箱重'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='CtnWegtCla',
            field=models.IntegerField(blank=True, null=True, verbose_name='箱重等级'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='DesPort',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目的港'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='DesPortNam',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目的港全称'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='Owner',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='持箱人'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='PrpSig',
            field=models.IntegerField(blank=True, choices=[(0, '否'), (1, '是')], null=True, verbose_name='配载'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='Size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='StaPort',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='起运港'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='UnloadPort',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='卸货港'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='Vessel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='船名'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='Voyage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='航次'),
        ),
        migrations.AlterField(
            model_name='yard_cur_cons',
            name='YardCel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='场箱位'),
        ),
    ]
