# Generated by Django 2.2 on 2019-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardMon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armg_op_plan',
            name='PreOpCtnNum',
            field=models.IntegerField(blank=True, null=True, verbose_name='紧前作业箱数'),
        ),
    ]
