# Generated by Django 2.2 on 2019-05-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesselStruct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ves_bay_lay_struct',
            name='BayCanOpe',
        ),
        migrations.RemoveField(
            model_name='ves_bay_lay_struct',
            name='BayLayCanOpe',
        ),
        migrations.AlterField(
            model_name='ves_bay_lay_struct',
            name='BayHigh',
            field=models.IntegerField(blank=True, null=True, verbose_name='离底层(该层层号)'),
        ),
    ]
