# Generated by Django 2.2 on 2019-05-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vesselStruct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='con_sto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.CharField(max_length=50, verbose_name='船名')),
                ('Voyage', models.CharField(max_length=50, verbose_name='航次')),
                ('VesCellNo', models.CharField(max_length=50, verbose_name='船箱位')),
                ('ColNo', models.CharField(max_length=50, verbose_name='列号')),
                ('DeckCagSig', models.CharField(max_length=50, verbose_name='甲板or舱内')),
                ('CtnNo', models.CharField(max_length=50, verbose_name='箱号')),
                ('CtnTyp', models.CharField(max_length=50, verbose_name='箱型')),
                ('Size', models.CharField(max_length=50, verbose_name='尺寸')),
                ('Status', models.CharField(max_length=50, verbose_name='状态')),
                ('CtnWegt', models.FloatField(verbose_name='箱重')),
                ('GForce', models.CharField(max_length=1000, verbose_name='货特要求')),
                ('StaPort', models.CharField(max_length=50, verbose_name='起运港')),
                ('UnloadPort', models.CharField(max_length=50, verbose_name='卸货港')),
                ('DesPort', models.CharField(max_length=50, verbose_name='目的港')),
                ('CtnOpeSta', models.CharField(max_length=50, verbose_name='箱作业状态')),
                ('YardCel', models.CharField(max_length=50, verbose_name='堆场箱位')),
            ],
        ),
        migrations.CreateModel(
            name='con_stowage_import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vessel', models.CharField(max_length=50, verbose_name='船名')),
                ('Voyage', models.CharField(max_length=50, verbose_name='航次')),
                ('VesCellNo', models.CharField(max_length=50, verbose_name='船箱位')),
                ('ColNo', models.CharField(max_length=50, verbose_name='列号')),
                ('DeckCagSig', models.CharField(max_length=50, verbose_name='甲板or舱内')),
                ('CtnNo', models.CharField(max_length=50, verbose_name='箱号')),
                ('CtnTyp', models.CharField(max_length=50, verbose_name='箱型')),
                ('Size', models.CharField(max_length=50, verbose_name='尺寸')),
                ('Status', models.CharField(max_length=50, verbose_name='状态')),
                ('CtnWegt', models.FloatField(verbose_name='箱重')),
                ('Owner', models.CharField(max_length=50, verbose_name='持箱人')),
                ('GForce', models.CharField(max_length=1000, verbose_name='货特要求')),
                ('StaPort', models.CharField(max_length=50, verbose_name='起运港')),
                ('UnloadPort', models.CharField(max_length=50, verbose_name='卸货港')),
                ('DesPort', models.CharField(max_length=50, verbose_name='目的港')),
                ('StrPickAwayCtn', models.CharField(max_length=50, verbose_name='直提箱')),
                ('CtnOpeSta', models.CharField(max_length=50, verbose_name='箱作业状态')),
                ('PlaCtnCel', models.CharField(max_length=50, verbose_name='计划箱位')),
            ],
        ),
    ]
